env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: [{ files: "lib/*.ts" }]
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
rules: { "@typescript-eslint/explicit-function-return-type": "off" }
